### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by joelhandwell** [OpenDDRdotORG/OpenDDR-Resources#27]
I was wondering if this project still active. Is there any future plan or alternative suggested?

**Comment by joelhandwell** [comment]
@OpenDDR any news?

**Comment by mkorostoff** [comment]
Just as a casual observer, I'm pretty sure this project is dead.  I think the successor is https://devicemap.apache.org/index.html

**Comment by keilw** [comment]
Yes please provide JIRA tickets there (unless you are an Apache committer already with e.g. a Patch file or similar suggested code/data sample attached)

**Comment by OpenDDR** [comment]
It is not dead at all. @MKorostoff on the contrary, DeviceMap was archived since 'data' the way OpenDDR or devicemap-data looks like could not be properly maintained by ASF in a way members of the community asked us to do (e.g. via a web-interface similar to e.g. http://mobiledetect.net/. OpenDDR is the primary successor to DeviceMap, see http://attic.apache.org/projects/devicemap.html. Please file issues or PRs against https://github.com/OpenDDRmobi/openddr-data. For structural consistency and backward compatibility with DeviceMap everything is under https://github.com/OpenDDRmobi. This organization and repo is to retain its history (unlike WURFL we don't delete things or try to rewrite history ;-D ) and for clients or projects based on the old DDRs. The new versions from 1.31 on can be found on https://github.com/OpenDDRmobi/openddr-data, BinTray/JCenter or MavenCentral. I will not reopen this, but please file any issues under https://github.com/OpenDDRmobi now.

**Comment by mkorostoff** [comment]
@OpenDDR thanks for the reply, glad to hear you're back in action.  To be clear, am I correct in understanding that _the project_ is ongoing but this specific repository is dead?  If so, may I suggest an update to the readme stating as much?

**Comment by OpenDDR** [comment]
Will do, thanks a lot for your patience and feedback. We started adding http://openddr.mobi to both the organization and this user, but updating Readme for certain repositories, yes, we also shall do that soon.
One or the other repo, e.g. the New Language Template could even be transferred or rebuilt completely, but the others stay here for historic reasons, just like Apache DeviceMap in the attic.
